export const dummyData = [
  {
    id: "1",
    name: "Andrew",
    homeLocation: "Jurong",
    workLocation: "Tampines",
    plannedActivity: "yes",
    activityDetails: "Badminton",
    activityLocation:"Bedok",
  },
  {
    id: "2",
    name: "Johnny",
    homeLocation: "Bedok",
    workLocation: "Yishun",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "3",
    name: "Manyu",
    homeLocation: "Jurong",
    workLocation: "Tuas",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "4",
    name: "Bindu",
    homeLocation: "Punggol",
    workLocation: "PayaLebar",
    plannedActivity: "",
    activityDetails: "",
    activityLocation: "",
  },
  {
    id: "5",
    name: "Wong",
    homeLocation: "Bishan",
    workLocation: "Yishun",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "6",
    name: "Sanya",
    homeLocation: "Jurong West",
    workLocation: "Ubi",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "7",
    name: "Francis",
    homeLocation: "Tampines",
    workLocation: "Bugis",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "8",
    name: "Wee Chin",
    homeLocation: "Orchard",
    workLocation: "Redhill",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
  {
    id: "9",
    name: "Farah",
    homeLocation: "Sengkang",
    workLocation: "Tampines",
    plannedActivity: "",
    activityDetails: "",
    activityLocation: "",
  },
  {
    id: "10",
    name: "Reshmia",
    homeLocation: "Joo Seng",
    workLocation: "Chinatown",
    plannedActivity: "",
    activityDetails: "",
    activityLocation:"",
  },
];